### ISSUE TITLE
how to use this without $ symbol

### ISSUE THREAD

**Issue by uresh** [LeaVerou/awesomplete#16739]

**Comment by LeaVerou** [comment]
Not sure I understand the question.

**Comment by Nexi** [comment]
How to use it without jQuery maybe? I'm trying to use it with React, and I have something like this:

```
applyAutocomplete(component){
        const $inputElement = React.findDOMNode(component);
        let awesomplete     = new Awesomplete($inputElement,  {
            list: ["Ada", "Java", "JavaScript", "Brainfuck", "LOLCODE", "Node.js", "Ruby on Rails"]
        });
    }

    renderInput({ name }){
        return (
            <div>
                <label>{ name }</label>
                <input ref={(component) => { this.applyAutocomplete(component)}} type="text"/>
            </div>
        );
    }
```

and I'm getting error:
awesomplete.min.js:3 Uncaught TypeError: Cannot read property 'setAttribute' of null

**Comment by ansballard** [comment]
This thread is pretty old, but I ran into the same issue trying to build an angular directive. Turns out I was trying to feed the constructor an array of elements instead of a single element, so it couldn't find the methods on the single element. jQuery isn't a dependency (Looks like `$` is just an internal alias the library uses?), so it's probably an issue with how you're getting/feeding in the element you want to attach to.

**Comment by vlazar** [comment]
Use `Awesomplete.$` to find single DOM element.
Use `Awesomplete.$$` to find multiple DOM elements.

In examples `Awesomplete.$` and `Awesomplete.$$` are aliased as globals `$` and `$$`,

@uresh Closing since you haven't provided any detailed description.
