### ISSUE TITLE
Using remote JSON data of web service as data source

### ISSUE THREAD

**Issue by nishvs** [LeaVerou/awesomplete#16769]
I wanted to use a json array which is returned from a web service as data source?? How can i do it??

**Comment by blazarfox** [comment]
Her site [ http://leaverou.github.io/awesomplete/ ]  has a few HTML examples. In this case I suppose it would depend on what you are using to fetch the json. Here is one example from that site. 

``` html
<input class="awesomplete" list="mylist" />
<datalist id="mylist">
    <option>Ada</option>
    <option>Java</option>
    <option>JavaScript</option>
    <option>Brainfuck</option>
    <option>LOLCODE</option>
    <option>Node.js</option>
    <option>Ruby on Rails</option>
</datalist>
```

If you used something like angular to fetch the array data then you could so something like this.

``` html
<input class="awesomplete" list="mylist" />
<datalist id="mylist">
    <option ng-repeat="item in main.myList">{{ item }}</option>
</datalist>
```

In this example main is the assumed short name for the controller used and myList is the variable in that controller where the array was stored. This is also assuming that the json returned isn't fetched from a database or has multiple values for each item. In that case you would have to do something like `{{ item.name }}` if you received something like 

``` javascript
{ 
   name: "javascript" 
} 
```

This is obviously a very basic example without knowing the implementation. 

I also apologize if there are any errors. I am writing this from a mobile phone.

Edit: fixes to markdown

**Comment by nishvs** [comment]
I tried that anthony but it is not working. I am using a list as a datasource and using awesomplete. Intially data list is empty and when input is provided then i am creating awesomplete object using the data fetched from the webservice. But i am unable to make it all work together.

**Comment by blazarfox** [comment]
Ok, I will put a plunkr or something together as soon as I can.

**Comment by nishvs** [comment]
Thanks a lot Anthony.

**Comment by blazarfox** [comment]
I put this plunker together => http://plnkr.co/edit/07Ol6FsmPk3EqDcReWCX?p=preview
I should note however, that I too could not get what I received back as JSON to work.  The datalist populates, and without the 'awesomplete' class the dropdown list works fine.  If you add the class it just doesn't seem to work.  I tested using an object list and an array list returned as JSON, and then similar information created locally.  Only the locally created objects work.  I will try to dive into this a bit further but would appreciate it if anyone could shed some light on this.

**Comment by nishvs** [comment]
Yes same thing happened for me. I guess it cannot be used with when the datasource is populated from the result of a web service.

Another problem which could have occurred as per my guess is Awesomplete is using the datalist before the Angular binds the data from webservice. So only no words come up in autocomplete feature.
What do you say??

**Comment by herregroen** [comment]
Awesomplete only evaluates the datalist element when it's list property is assigned. Which, if you're using the awesomplete class is only on page load.

If you want it to pick up changes you should reassign the datalist's id to awesomplete's list property ( to the actual instance, not the input element ). For example this reloads all the lists of all Awesomplete elements:

``` js
  for(var i = 0; i < Awesomplete.all.length; i++){
    Awesomplete.all[i].list = Awesomplete.all[i].list;
  }
```

Of course you'd rather just reassign the one instance that's actually being used instead of all of them. But as a quick and dirty solution you could just call the above function in whatever ajax callback angular has.

**Comment by nishvs** [comment]
It is not working if i apply the above solution.

My script is:

//Awesomplete --START
        var input = document.getElementById("location");

```
    $(input).on("keyup", function(){

    $.ajax({
    url: 'http://localhost:4000/api/getlocation',
    type: 'GET',
    dataType: 'json'
    })
      .success(function(data) {
      console.log(data)
      var temp = "";
      var list = [];
      $.each(data, function(key, value) {
        temp = temp +"<li>"+value.name+"</li>"
      });
      console.log("chk : "+temp);
      document.getElementById("dataSource").innerHTML = temp
      //document.getElementById("location").setAttribute("data-list", temp);
      //awesomplete.list = list;
      for(var i = 0; i < Awesomplete.all.length; i++){
Awesomplete.all[i].list = Awesomplete.all[i].list;
```

 }
          });
      })

```
  //Awesomplete --END
```

And my html is

```
<input type="text" name="location" class="awesomplete form-control" data-list="#dataSource" id="location"  ></input>
                      <ul id="dataSource" style="display:none">
                      </ul>
```

**Comment by herregroen** [comment]
Ah, right. My bad.

The javascript set function only executes if the value actually changed.

Can you try this one?

``` js
  for(var i = 0; i < Awesomplete.all.length; i++){
    var list = Awesomplete.all[i].list;
    Awesomplete.all[i].list = undefined;
    Awesomplete.all[i].list = list;
  }
```

And yes, this is incredibly hacky. So adding a reload function that rescans the list property could be useful functionality.

**Comment by nishvs** [comment]
I tried this but it is not working with the code which i provided earlier. Can u tell what i am doin wrong???

**Comment by blazarfox** [comment]
I updated my Plunker here -> http://plnkr.co/edit/07Ol6FsmPk3EqDcReWCX?p=preview

I was able to resolve the issue using Angular by manually adding the data to the list once the ajax request is finished. Once I get a bit more time I can see if I can do the same in Jquery if you would like.

EDIT:  Side note.  I noticed that even creating the Awesomplete object rather than using the HTML class, if I created the class with the finished list it still didn't work.  I had to create the Awesomplete object and then manually add it to the new objects ._list method.  This seems to have done the trick.  Another thing to note is that I had to iterate over the JSON to create an array.

**Comment by blazarfox** [comment]
I was able to get the Jquery working as well, but not updating frequently as you were going for.  When it updates on the 'keyup' event the input box loses focus and cancels the Awesomplete pop-up event (it will sometimes appear very briefly before disappearing).  I don't really see that as a bug with Awesomplete though.  I can't say that I am extremely familiar with Jquery so I am not sure how to remedy that issue.

EDIT: I got to spend a little bit more time on it and I was able to add in your keyup event for Jquery.  Truely it should be a function call since it is mostly duplicated code, but as its late and I should be heading off to bed, I think this will have to do for now :)  I hope this helps, nishvs!

**Comment by blazarfox** [comment]
Did either mine or herregroens suggestions help resolve your issue?

**Comment by nishvs** [comment]
Yes it worked out. Sorry for late reply i was busy with some work. Thanks to Auzarius and herregroens. I wanted to ask one more thing the solution which u guys hav suggested would reload the datasource for all the controls in the page with awesomplete class or only the one textbox which is selected based on ID.

**Comment by blazarfox** [comment]
Would you be able to provide a plunker or link as an example to the kind of setup you are using? That would make it easier to tailor it to your specific usage.
