### ISSUE TITLE
multiple data selection not working

### ISSUE THREAD

**Issue by tolry** [LeaVerou/awesomplete#16801]
Hi there,

great library, but I am having trouble getting multiple data selection to work. Here is a minimal example for reproduction

http://codepen.io/anon/pen/KVzbJj

Any idea, why this is not working as intended? I tried using data-list attribute as well as a complete data-list tag. In my application (not in the codepen above) I also tried configuring the setting in JS rather than HTML. I tried taking a look at the code, but could not find the segment dealing with this feature.

Any help is appreciated, thanks.

**Comment by vlazar** [comment]
You need some custom JS code in addition to just including `awesomplete.js` on the page and using `data-multiple`.

@LeaVerou It's a visual bug in docs. JS part is not visible in Advanced Examples section.

**Comment by TxHawks** [comment]
@LeaVerou - The invisible js examples seem to be caused by bad Prism urls.

Because the Prism css isn't there, the `script` tags inside the `pre` tags are set to `display: none'.

I would have sent a pull request, but not sure where do you want to link to Prim from

**Comment by tolry** [comment]
@vlazar @TxHawks thanks, that was the information I was missing.

I will close here.

**Comment by LeaVerou** [comment]
Oops, thanks for spotting that!
I think it makes sense to download a distro of Prism and include it in the repo.

**Comment by hotaryuzaki** [comment]
i had same problem, im using an example from the docs.
and i already tried load prism from my local sources too.
but still not worked.

i understand the "data-multiple" just for identify the input element, but i still didnt get it how to solved this issue.
could you show me an example to work it out?

*sorry for my bad english

**Comment by vlazar** [comment]
@hotaryuzaki The **Multiple values** example in [Advanced Examples](http://leaverou.github.io/awesomplete/#advanced-examples) section should work just fine.

**Comment by hotaryuzaki** [comment]
oh, it works?
hmm..

sorry, i need your help, why my code isn't working?

`<input type="text" class="awesomplete span12" data-list="Ada, Java, JavaScript, Brainfuck, LOLCODE, Node.js, Ruby on Rails"  data-multiple="" data-minchars="1"  />`

and JS just like in Advances Examples

`<input type="text" class="awesomplete span12" data-list="Ada, Java, JavaScript, Brainfuck, LOLCODE, Node.js, Ruby on Rails"  data-multiple="" data-minchars="1" autocomplete="off" aria-autocomplete="list" />

```
                <script>
                new Awesomplete($('input[data-multiple]'), {
                    filter: function(text, input) {
                        return Awesomplete.FILTER_CONTAINS(text, input.match(/[^,]*$/)[0]);
                    },

                    replace: function(text) {
                        var before = this.input.value.match(/^.+,\s*|/)[0];
                        this.input.value = before + text + ", ";
                    }
                });
                </script>`
```

Note that i already include the Awesomplete JS and CSS

**Comment by vlazar** [comment]
The HTML piece in Multiple values examples does not include `class="awesomplete"`. You need to remove it.

If you include this class the completer would be automatically instantiated already. It's for simple cases when you init list from HTML, exactly like in example:

``` html
<input data-list="CSS, JavaScript, HTML, SVG, ARIA, MathML" data-multiple />
```

**Comment by hotaryuzaki** [comment]
really...i feel stupid.. haha..
because, it's still not work, i didnt get it why, and i dont know where is wrong with my code.
so i decide to create code from plain like this :

``` html
<html lang="en">
<head>
<link rel="stylesheet" href="http://localhost/awesomplete/inc/awesomplete.css" />
<script src="http://localhost/awesomplete/inc/awesomplete.min.js" async></script>
<script>
new Awesomplete($('input[data-multiple]'), {
    filter: function(text, input) {
        return Awesomplete.FILTER_CONTAINS(text, input.match(/[^,]*$/)[0]);
    },

    replace: function(text) {
        var before = this.input.value.match(/^.+,\s*|/)[0];
        this.input.value = before + text + ", ";
    }
});
</script>
</head>
<body>
<div class="awesomplete">
<form method="POST">
<input class="" data-list="CSS, JavaScript, HTML, SVG, ARIA, MathML" data-multiple />
</form>
</div>
</body>
</html>
```

and what i get:
- still not work
- just like normal html text input tag

1 error on browser:
- Uncaught ReferenceError: Awesomplete is not defined

what i did:
- put JS in head section
- put JS before input tag
- put JS after input tag
- put div tag
- check awesomplete CSS & JS path
- change static/relative path

Sorry if i bother you with this simple question..
you can call me a newbie, hehe.. :)

**Comment by vlazar** [comment]
1. Unless you run inline script on DOM ready event somehow, e.g. with jQuery, you should include inline script tag AFTER `<input>`
2. You need to use `Awesomplete.$` instead of just `$`, because `$` shortcut was created in docs and not by Awesomplete itself. You can also do it yourself `var $ = Awesomplete.$;`
3. You need to remove `async` attribute if you are not using DOM ready. See https://github.com/LeaVerou/awesomplete/issues/16765#issuecomment-160541109

**Comment by LeaVerou** [comment]
>  DOM ready event somehow, e.g. with jQuery

or just the `DOMContentLoaded` event.

**Comment by hotaryuzaki** [comment]
thx bro. it really works!!
what i do :
- remove async
- JS works when i put on DOM ready with jquery. Or include inline script tag AFTER <input>

oh how simple is that (i feel more stupid haha), thx its because your guide obviously..
and thanks for the owner and contributors for this great library..
