### ISSUE TITLE
Outdated npm version

### ISSUE THREAD

**Issue by powerbuoy** [LeaVerou/awesomplete#16850]
I get:
argument `$saturation` of `hsl($hue, $saturation, $lightness)` must be between 0 and 100

Backtrace:
node_modules/awesomplete/awesomplete.css:91, in function `hsl`

And here's what line 91 looks like:

background: hsl(68, 101%, 41%);

Would be lovely if this could be fixed so that we can keep awesomplete as a node module.

**Comment by vlazar** [comment]
Several issues:
1. The awesomplete 1.0.0 npm package has been already published by some other guy 7 months ago https://www.npmjs.com/package/awesomplete
2. The code in published 1.0.0 npm package it is very outdated - April 2015
3. The 101% issue was fixed a long time ago in 815071c3ea0dda9da45ae1e11add9305bcfb55b4
4. There are tons of other fixes and improvements since 1.0.0 made in this repo

@LeaVerou Can you please contact npm support and release new awesomplete package by yourself? There is no point releasing 1.0.0, since it's already released and version in package.json is 0.0.0 while git tag at this point is 1.0.0. So how about a 1.1.0 npm release with current code?

Handling Module Name Disputes
https://docs.npmjs.com/misc/disputes

Synopsis

> Get the author email with npm owner ls <pkgname>
> Email the author, CC support@npmjs.com
> After a few weeks, if there's no resolution, we'll sort it out.

There is also a bower.son, so I guess this should be also updated to 1.1.0 and match new 1.1.0 git tag.

I can prepare code for release, but I can't publish npm package for obvious reason.

**Comment by LeaVerou** [comment]
@stubbornella, perhaps you can help?

**Comment by vlazar** [comment]
@LeaVerou @stubbornella Any progress on this?

**Comment by LeaVerou** [comment]
I pinged her privately.

**Comment by LeaVerou** [comment]
The guy who published it on npm is @bequadrat. 
@bequadrat, could you please transfer the npm package to me? Thanks!

**Comment by LeaVerou** [comment]
@vlazar I just `npm publish`ed again, as the package was deleted, but now the version is 0.0.0! Why did we not have a sensible version in package.json?

**Comment by vlazar** [comment]
Lea, first of all, should it be 1.1 or 2.0 ? https://github.com/LeaVerou/awesomplete/issues/16873#issuecomment-197444167

Then I need to update package.json and add minified version. And update changeling, since you are trying to publish it now.

**Comment by LeaVerou** [comment]
I was publishing the previous version @vlazar, as @bequadrat unpublished it.

**Comment by LeaVerou** [comment]
And, I think the new version should be 1.1. It's not THAT huge of a change.

**Comment by vlazar** [comment]
OK, but there are breaking changes and people are asking about semver.

**Comment by vlazar** [comment]
> I was publishing the previous version @vlazar, as @bequadrat unpublished it.

This version was published from the 1.0 tag and the version in package.json at this tag was 0.0.0

**Comment by vlazar** [comment]
> Then I need to update package.json and add minified version. And update changeling, since you are trying to publish it now.

Done. Ready for 1.1.0.

**Comment by LeaVerou** [comment]
The version in package.json should be in sync with the git tag...
Anyhow, should I publish 1.1?

**Comment by vlazar** [comment]
Sure, the 1.1 is ready, unless you want to name it 2.0 to satisfy expectations like https://github.com/LeaVerou/awesomplete/issues/16873

I'm not sure if it's possible to publish 1.0 now. You can try to unpublish, then checkout `v1.0.0` tag, fix version in `package.json` and try publish again.

But according to https://docs.npmjs.com/cli/unpublish

> Even if a package version is unpublished, that specific name and version combination can never be reused. In order to publish the package again, a new version number must be used.

Maybe it's for same author only, since you only published 0.0.0, you can try to publish 1.0.0

**Comment by vlazar** [comment]
One more thought, npm badge!

**Comment by LeaVerou** [comment]
Eh, whatever. Since we have a new version, it doesn't matter anymore.
v1.1 published!

**Comment by emmenko** [comment]
Wow, that was quick :)

Thanks for start using semver!

**Comment by emmenko** [comment]
Btw: if you use [commitizen](https://www.npmjs.com/package/commitizen) with the [conventional changelog](https://www.npmjs.com/package/cz-conventional-changelog) you get changelogs generated for free.

**Comment by ramauf** [comment]
q
