### ISSUE TITLE
Uncaught TypeError: this.input.setAttribute is not a function

### ISSUE THREAD

**Issue by fmpoffice** [LeaVerou/awesomplete#16889]
Uncaught TypeError: this.input.setAttribute is not a function？

`<input data-list="CSS, JavaScript, HTML, SVG, ARIA, MathML" data-multiple />`
`new Awesomplete($('input[data-multiple]'), {
    filter: function(text, input) {
        return Awesomplete.FILTER_CONTAINS(text, input.match(/[^,]*$/)[0]);
    },`

```
replace: function(text) {
    var before = this.input.value.match(/^.+,\s*|/)[0];
    this.input.value = before + text + ", ";
}});`
```

**Comment by vlazar** [comment]
Can you be more specific?

Same code from **_Multiple values**_ example in [Advanced Examples](http://leaverou.github.io/awesomplete/#advanced-examples) works.

**Comment by Aigzy** [comment]
You can't use `$()` from jQuery to select your input.
Use `document.getElementById()` instead

**Comment by Sundevil96** [comment]
ShitHub fails to recognize my username and password so I cannot make your asinine contributions to the nothingness of being stop. you should recommend as I did to the dumbasses who maintain the site it incorporate current methods that allow users to abandon the pathetic platform.

**Comment by Etherian** [comment]
I am receiving the same error. The version I downloaded was last updated May 16 -- so I guess commit d2c34cff7fc0f02c04e9c395c98dfdcf38c9773a. The error occurs on line 16 of awesomplete.js:

``` javascript
var _ = function (input, o) {
    var me = this;

    // Setup

    this.input = $(input);
    this.input.setAttribute("autocomplete", "off"); //Uncaught TypeError: this.input.setAttribute is not a function
    this.input.setAttribute("aria-autocomplete", "list");
...
```

I am new to Javascript, but it looks like the problem is that on line 15 _this.input_ is assigned a jQuery object, which does not have a _setAttribute_ method. I tried blindly changing line 15 to

``` javascript
this.input = $(input)[0];
```

but another error occurred later in the script, on line 356:

``` javascript
for (var i in o) {
    var val = o[i];

    if (i === "inside") {
        $(val).appendChild(element);
    }
    else if (i === "around") {
        var ref = $(val);
        ref.parentNode.insertBefore(element, ref); //Uncaught TypeError: Cannot read property 'insertBefore' of undefined
        element.appendChild(ref);
    }
...
```

**Comment by LeaVerou** [comment]
Awesomplete doesn't use jQuery. The `$()` method is returning an element.

**Comment by Etherian** [comment]
I see. Awesomplete defines its own internal $ function. The trouble was that _I_ was accidentally feeding it a jQuery object.

**Comment by vlazar** [comment]
Removed some global `$()` usage in docs, which probably caused this confusion 5ca39214896ba58c765fcb2b1c3acf992b6e1b99

**Comment by JenPhD** [comment]
I'm still getting this error for line 15. Uncaught TypeError: Cannot read property 'setAttribute' of null. Any thoughts?

**Comment by JenPhD** [comment]
I think I know what the problem is, or I have a theory. I just don't know how to fix it. I'm using handlebars, and the user does not enter any information on the landing page, but the awesomplete data list is in the app.js file, so I think it is looking for something that doesn't exist until the user signs in. When the user signs in, there are input boxes with awesomplete. And, it works. It is just bothering me that I am getting this error in the console when the landing page loads. Not sure how to fix it and open to suggestions.

**Comment by vlazar** [comment]
@JenPhD Can you share a reproducible example on https://jsfiddle.net/ ?
