### ISSUE TITLE
Invalid Syntax on IE8

### ISSUE THREAD

**Issue by cnsgithub** [LeaVerou/awesomplete#16985]
Hi, I know -2016 ;) 
But unfortunately even using this script will cause IE8 to stop loading any subsequent script and the whole site becomes unusable due to get set syntax (Expected identifier ':'

Maybe consider to not use get set in future or provide an alternative way. 

Anyway just a suggestion - I've fixed it by using regular functions e.g

```
getIsOpened: function(o) {
    return this.isOpened;
},
```

**Comment by LeaVerou** [comment]
You want us to not use something today, because a browser that was released 7 years ago and has a market share of 1.46% won't recognize it? Do you want a list of all the syntax IE5 and IE6 don't recognize? Should we not use that too?

This `getIsOpened` is disgusting. Is this Java? You do realize that `this.isOpened` is not actually private, right?

If you don't want one script's error to break all your other scripts, don't bundle them. Clearly, you've concatenated all your scripts into one, which is why this happens.
And while we're at it how about you follow progressive enhancement and make sure your site doesn't "become unusable" if JavaScript doesn't run?
