### ISSUE TITLE
Handle Arrow Keys selection for dropdown elements, unable to traverse the list using down arrow key

### ISSUE THREAD

**Issue by IUnLife** [LeaVerou/awesomplete#17014]
Arrow keys stops working when list is dynamically added to autocomplete.

.success(function(data) {
  var list = [];
  $.each(data, function(key, value) {
    list.push(value.name);
  });
  awesomplete.list = list;
});

http://codepen.io/SitePoint/pen/QbpjVG 
For example on above codepen, open the list and try to navigate using arrow keys, the ist and 2nd items are selected recursively.

**Comment by davidkna** [comment]
`keyup` is triggered when a key is released which also happens when you press you arrow keys.
Check for the keyCode before updating the list (like in the [awesomplete source](https://github.com/LeaVerou/awesomplete/blob/gh-pages/awesomplete.js#L61-L80) or listen to a different event type like `input` (less browser support) because setting the list causes a call to `awesomeplete.evaluate` which regenerates the suggestions list.

**Comment by IUnLife** [comment]
Can you please try above for the codepen i added. http://codepen.io/SitePoint/pen/QbpjVG

**Comment by yoelpenasadgo** [comment]
Hello! I'm just having this issue, but I solved like this:

I declared an array with the keycodes of 'arrow up' and 'arrow down' keys (38 and 40). And then I only update the list if the key that has been released is not in that array. (Alternative: "if e.keyCode != 38 && e.keyCode != 40..")
```javascript
    var arrowKeys = [38, 40];

    $(searchBox).keyup(function(e){
        var value = $(searchBox).val();
        if ($.inArray(e.keyCode, arrowKeys) == -1) {
            if (value.length > 2) { // Not related to the issue
                $.ajax({
                    url: "/api/suggestions/" + $.trim(value),
                    cache: false,
                    success: function (data) {
                        awesomplete.list = JSON.parse(data);
                    }
                });
            } else {
                awesomplete.list = [];
            }
        }
    });
```
Hope it works for you :)
