### ISSUE TITLE
A way to set the <mark> color

### ISSUE THREAD

**Issue by Frazer** [LeaVerou/awesomplete#17040]
some way to do this without diving in to the dom could be good.

.awesomplete mark{
	background: none !important;
	background-color: none !important;
}

**Comment by LeaVerou** [comment]
Writing your own CSS to customize the look of Awesomplete is exactly as things were intended. You don't need `!important` though. If you need extensive customizations, consider only including `awesomplete.base.css` instead of the entire CSS file. That one only contains the CSS styles needed by Awesomplete to function, and no styling.
