### ISSUE TITLE
ReferenceError: Can't find variable: Awesomplete

### ISSUE THREAD

**Issue by wildsky** [LeaVerou/awesomplete#17078]
```
<link rel="stylesheet" href="css/awesomplete.css" />

<script src="js/awesomplete.js" async></script>
  
<input id="myinput" />

<script>
	
	var input = document.getElementById("myinput");
	
	new Awesomplete(input, {
		list: [
			[ "Belarus", "BY" ],
			[ "China", "CN" ],
			[ "United States", "US" ]
		]
	});
	
</script>
```

The simpler usage works fine, but I need to have a label and separate id. But when trying to instantiate via JS, can't find the variable...

**Comment by davidkna** [comment]
That's because of the `async` attribute in `<script src="js/awesomplete.js" async></script>`: When your second script executes `js/awesomplete.js` hasn't been loaded and executed yet and `Awesomplete` isn't in the namespace yet.

You could fix this by removing the `async` attribute or by merging both scripts into a single file. You might need the `defer` attribute in that case instead.

**Comment by wildsky** [comment]
My eye skipped right over that. Thank you!

**Comment by eyalev** [comment]
Maybe put something in the documentation that warns about this? (Unless it's very trivial)

I wasted some time on this as well.

It's wired that some of the first examples don't work when copy-pasting them locally.

**Comment by LeaVerou** [comment]
> Maybe put something in the documentation that warns about this?

The great thing about open source projects is that if you feel strongly about something, you don't have to ask others to do what you want, you can do it yourself! 
Pull requests are always welcome, and for something so small, the chances of merging it are high. :)
