### ISSUE TITLE
Hyperlink support

### ISSUE THREAD

**Issue by tariqgm** [LeaVerou/awesomplete#17116]
Hello,

I just want to double confirm you support hyperlink. Suppose I would like to use for search and when an item find out then upon clicking would take you to target page.

Thank you

**Comment by LeaVerou** [comment]
Sounds like you need to use `awesomplete-select` http://leaverou.github.io/awesomplete/#events
Make sure to call `evt.preventDefault()` to prevent the text from being inserted and close the awesomplete instance manually from within the listener, since `evt.preventDefault()` will also prevent it from closing.

Let us know if you need any help with all of this!
