### ISSUE TITLE
Issue with Arabic and Persian Language

### ISSUE THREAD

**Issue by sadeghbarati** [LeaVerou/awesomplete#17210]
hello @LeaVerou thanks for your great plugin ❤️ 
as u see in `ul list` mark tag makes the Persian or Arabic text show separately

![Screenshot (16)](https://user-images.githubusercontent.com/17789047/70546270-36f6d300-1b84-11ea-9165-b47e4a285714.png)

``` html
<mark>He</mark>
"llo"
```
"Hello"

``` html 
<mark>مش</mark>
"هد"
```

"مش هد" :x: 
"مشهد" :heavy_check_mark:

**Comment by bbenjamin** [comment]
Hi @riiccardo - 
I attempted to reproduce your issue here:
https://codepen.io/bbbenjamin/pen/ZEbYROa

The issue reported with `<mark>` could not be reproduced.
<img width="206" alt="issue-17210" src="https://user-images.githubusercontent.com/1742345/79041619-2a7c9880-7bbf-11ea-9f61-e60e79dd94d7.png">
This is most likely specific to your site. My suspicion is CSS somewhere  is occurring there is CSS altering the default styling of `<mark>` so it's not `display: inline`.

I believe the Codepen is sufficient evidence that the maintainer can close this.

@riiccardo, if you feel otherwise you can open a new issue that includes a Codepen (or something similar) that reproduces the issue. That would confirm it's not specific to your site, and pretty much guarantees it will be addressed.
